insert into Widget (edlName, pydmName) values('ByteClass', 'PyDMByteIndicator');
insert into Widget (edlName, pydmName) values('RegTextupdateClass', NULL);
insert into Widget (edlName, pydmName) values('TextentryClass', 'PyDMLineEdit');
insert into Widget (edlName, pydmName) values('TextupdateClass', 'PyDMLineEdit');
insert into Widget (edlName, pydmName) values('TwoDProfileMonitorClass', NULL);
insert into Widget (edlName, pydmName) values('activeArcClass', 'PyDMDrawingArc');
insert into Widget (edlName, pydmName) values('activeBarClass', NULL);
insert into Widget (edlName, pydmName) values('activeButtonClass', '#PyDMPushButton');
insert into Widget (edlName, pydmName) values('activeChoiceButtonClass','PyDMEnumComboBox');
insert into Widget (edlName, pydmName) values('activeCircleClass', 'PyDMDrawingCircle');
insert into Widget (edlName, pydmName) values('activeCoefTableClass', NULL);
insert into Widget (edlName, pydmName) values('activeDynSymbolClass','#PyDMSymbol');
insert into Widget (edlName, pydmName) values('activeExitButtonClass','#PyDMPushButton');
insert into Widget (edlName, pydmName) values('activeGroupClass', 'QFrame');
insert into Widget (edlName, pydmName) values('activeIndicatorClass', NULL);
insert into Widget (edlName, pydmName) values('activeLineClass', 'PyDMDrawingLine');
insert into Widget (edlName, pydmName) values('activeMenuButtonClass','#PyDMRelatedDisplayButton');
insert into Widget (edlName, pydmName) values('activeMessageBoxClass',NULL);
insert into Widget (edlName, pydmName) values('activeMessageButtonClass','#PyDMPushButt');
insert into Widget (edlName, pydmName) values('activeMeterClass',NULL);
insert into Widget (edlName, pydmName) values('activeMotifSliderClass','PyDMSlider');
insert into Widget (edlName, pydmName) values('activeMpStrobeClass',NULL);
insert into Widget (edlName, pydmName) values('activePipClass','#PyDMEmbeddedDisplay#PyDMTabWidget');
insert into Widget (edlName, pydmName) values('activePngClass','PyDMDrawingImage');
insert into Widget (edlName, pydmName) values('activeRadioButtonClass','PyDMEnumComboBox');
insert into Widget (edlName, pydmName) values('activeRampButtonClass',NULL);
insert into Widget (edlName, pydmName) values('activeRectangleClass','PyDMDrawingRectangle');
insert into Widget (edlName, pydmName) values('activeSignalClass',NULL);
insert into Widget (edlName, pydmName) values('activeSliderClass',NULL);
insert into Widget (edlName, pydmName) values('activeSymbolClass','#PyDMSymbol');
insert into Widget (edlName, pydmName) values('activeVsBarClass',NULL);
insert into Widget (edlName, pydmName) values('activeXRegTextClass',NULL);
insert into Widget (edlName, pydmName) values('activeXTextClass','PyDMLabel');
insert into Widget (edlName, pydmName) values('activeXTextDspClass','PyDMLineEdit');
insert into Widget (edlName, pydmName) values('activeXTextDspClass:noedit', 'PyDMLineEdit');
insert into Widget (edlName, pydmName) values('includeWidgetClass',NULL);
insert into Widget (edlName, pydmName) values('menuMuxClass','#PyDMTabWidget');
insert into Widget (edlName, pydmName) values('pvInspectorClass', NULL);
insert into Widget (edlName, pydmName) values('relatedDisplayClass','PyDMRelatedDisplayButton');
insert into Widget (edlName, pydmName) values('shellCmdClass','PyDMShellCommand');
insert into Widget (edlName, pydmName) values('xyGraphClass',NULL);
insert into Widget (edlName, pydmName) values('cfcf6c8a_dbeb_11d2_8a97_00104b8742df',NULL);
insert into Widget (edlName, pydmName) values('activeTableClass',NULL);
insert into Widget (edlName, pydmName) values('activeUpdownButtonClass', '#PyDMDoubleSpinbox')
-- insert into Widget (edlName, pydmName) values(

